=== ilscipio/scipio-erp/framework/base/dtd/ofbiz-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<!--
Changes to this file: Copyright (C) Ilscipio GmbH. The changes are licensed
under the GNU Affero General Public License, version 3, or a commercial
license from Ilscipio GmbH (file LICENSE). The original code stays under
the Apache License, version 2.0, as stated above.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd" />

    <xs:complexType name="valueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required" />
                <xs:attribute ref="xml:space" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="resource">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property" />
            </xs:sequence>
            <xs:attribute name="global">
                <xs:annotation>
                    <xs:documentation>
                        If not specified, all label files named "*Labels.xml" are automatically included in global property-maps.
                        If set to false, prevents inclusion.
                        Labels from hot-deploy components automatically override those from framework and applications components
                        when combined in the global property-maps.
                        SCIPIO: 2.1.0: Added for global property-map support.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="true"/>
                        <xs:enumeration value="false"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="value" type="valueType" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="key" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ilscipio/scipio-erp/applications/marketing/config/MarketingEntityLabels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<!--
Changes to this file: Copyright (C) Ilscipio GmbH. The changes are licensed
under the GNU Affero General Public License, version 3, or a commercial
license from Ilscipio GmbH (file LICENSE). The original code stays under
the Apache License, version 2.0, as stated above.
-->
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/ofbiz-properties.xsd">
    <property key="ContactListType.description.ANNOUNCEMENT">
        <value xml:lang="de">Bekanntmachung</value>
        <value xml:lang="en">Announcement</value>
        <value xml:lang="es">Anuncio</value>
        <value xml:lang="fr">Annonce</value>
        <value xml:lang="it">Annunci</value>
        <value xml:lang="ja">告知</value>
        <value xml:lang="nl">Aankondiging</value>
        <value xml:lang="pt-BR">Anúncio</value>
        <value xml:lang="ro">Anunturi</value>
        <value xml:lang="th">การประกาศ</value>
        <value xml:lang="vi">Quảng bá</value>
        <value xml:lang="zh">声明</value>
        <value xml:lang="zh-TW">聲明</value>
    </property>
    <property key="ContactListType.description.MARKETING">
        <value xml:lang="de">Marketing</value>
        <value xml:lang="en">Marketing</value>
        <value xml:lang="es">Marketing</value>
        <value xml:lang="fr">Marketing</value>
        <value xml:lang="it">Vendite</value>
        <value xml:lang="ja">マーケティング</value>
        <value xml:lang="nl">Marketing</value>
        <value xml:lang="pt-BR">Marketing</value>
        <value xml:lang="ro">Vanzari</value>
        <value xml:lang="th">การตลาด</value>
        <value xml:lang="vi">Tiếp thị</value>
        <value xml:lang="zh">市场宣传</value>
        <value xml:lang="zh-TW">行銷</value>
    </property>
    <property key="ContactListType.description.NEWSLETTER">
        <value xml:lang="de">Newsletter</value>
        <value xml:lang="en">Newsletter</value>
        <value xml:lang="es">Carta de información</value>
        <value xml:lang="fr">Lettre d'information</value>
        <value xml:lang="it">Newsletter</value>
        <value xml:lang="ja">ニュースレター</value>
        <value xml:lang="nl">Nieuwsbrief</value>
        <value xml:lang="pt-BR">Mala direta</value>
        <value xml:lang="ro">Noutati</value>
        <value xml:lang="th">จดหมายข่าว</value>
        <value xml:lang="vi">Nhận tin mới</value>
        <value xml:lang="zh">新闻</value>
        <value xml:lang="zh-TW">新聞</value>
    </property>
    <property key="SegmentGroupType.description.MARKET_SEGMENT">
        <value xml:lang="de">Marktsegment</value>
        <value xml:lang="en">Market Segment</value>
        <value xml:lang="es">Segmento de marketing</value>
        <value xml:lang="fr">Segment de marché</value>
        <value xml:lang="it">Segmento di Mercato</value>
        <value xml:lang="ja">市場セグメント</value>
        <value xml:lang="nl">Marktsegment</value>
        <value xml:lang="pt-BR">Segmento de marketing</value>
        <value xml:lang="ro">Segment de Piata</value>
        <value xml:lang="th">ส่วนของการตลาด</value>
        <value xml:lang="vi">Phân khúc thị trường</value>
        <value xml:lang="zh">市场分区</value>
        <value xml:lang="zh-TW">市場分區</value>
    </property>
    <property key="SegmentGroupType.description.SALES_SEGMENT">
        <value xml:lang="de">Sales Segment</value>
        <value xml:lang="en">Sales Segment</value>
        <value xml:lang="es">Segmento de ventas</value>
        <value xml:lang="fr">Segment de vente</value>
        <value xml:lang="it">Segmento di Vendita</value>
        <value xml:lang="ja">販売セグメント</value>
        <value xml:lang="nl">Salessegment</value>
        <value xml:lang="pt-BR">Segmento de vendas</value>
        <value xml:lang="ro">Segment de Vanzare</value>
        <value xml:lang="th">ส่วนของการขาย</value>
        <value xml:lang="vi">Phân khúc kinh doanh</value>
        <value xml:lang="zh">销售分区</value>
        <value xml:lang="zh-TW">銷售分區</value>
    </property>
    <property key="TrackingCodeType.description.ACCESS">
        <value xml:lang="de">Zugangs-Code</value>
        <value xml:lang="en">Access Code</value>
        <value xml:lang="fr">Code d'accès</value>
        <value xml:lang="it">Codice di accesso</value>
        <value xml:lang="ja">アクセスコード</value>
        <value xml:lang="pt-BR">Código de acesso</value>
        <value xml:lang="vi">Mã truy nhập</value>
        <value xml:lang="zh">访问码</value>
        <value xml:lang="zh-TW">存取碼</value>
    </property>
    <property key="TrackingCodeType.description.EXTERNAL">
        <value xml:lang="de">Extern</value>
        <value xml:lang="en">External</value>
        <value xml:lang="es">Externo</value>
        <value xml:lang="fr">Externe</value>
        <value xml:lang="it">Esterno</value>
        <value xml:lang="ja">外部</value>
        <value xml:lang="nl">Extern</value>
        <value xml:lang="pt-BR">Externo</value>
        <value xml:lang="ro">Extern</value>
        <value xml:lang="th">ภายนอก</value>
        <value xml:lang="vi">Hệ thống ngoài</value>
        <value xml:lang="zh">外部</value>
        <value xml:lang="zh-TW">外部</value>
    </property>
    <property key="TrackingCodeType.description.INTERNAL">
        <value xml:lang="de">Intern</value>
        <value xml:lang="en">Internal</value>
        <value xml:lang="es">Interno</value>
        <value xml:lang="fr">Interne</value>
        <value xml:lang="it">Interno</value>
        <value xml:lang="ja">内部</value>
        <value xml:lang="nl">Intern</value>
        <value xml:lang="pt-BR">Interno</value>
        <value xml:lang="ro">Intern</value>
        <value xml:lang="th">ภายใน</value>
        <value xml:lang="vi">Nội bộ</value>
        <value xml:lang="zh">内部</value>
        <value xml:lang="zh-TW">內部</value>
    </property>
    <property key="TrackingCodeType.description.PARTNER_MGD">
        <value xml:lang="de">Unter Partner Verwaltung</value>
        <value xml:lang="en">Partner Managed</value>
        <value xml:lang="es">Partner</value>
        <value xml:lang="fr">Géré par un tiers</value>
        <value xml:lang="it">Gestito da un Partner</value>
        <value xml:lang="ja">パートナー</value>
        <value xml:lang="nl">Partner</value>
        <value xml:lang="pt-BR">Parceiro</value>
        <value xml:lang="ro">Gestit de un Partener</value>
        <value xml:lang="th">หุ้นส่วนการควบคุม</value>
        <value xml:lang="vi">Đối tác</value>
        <value xml:lang="zh">已管理的伙伴</value>
        <value xml:lang="zh-TW">團體</value>
    </property>
</resource>
